waiting_room:
  world: 'world'
  spawn_point:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  border:
    radius: 200.0
    damage: 0.0
    damage_buffer: 0.0

games:
  pvprun:
    maps:
      test:
        enabled: true

  skywars_rush:
    maps:
      test:
        world: 'world'
        enabled: true
        center:
          x: 100.0
          y: 100.0
          z: 0.0
        border:
          radius: 100.0
          damage: 0.0
          damage_buffer: 0.0
        chests:
          distance:
            spawn: 10.0
            center: 5.0
        spawn_points:
          teams:
            red:
              0:
                x: 136.5
                y: 107.0
                z: 0.5
                yaw: 180
                pitch: 0.0
            orange:
              0:
                x: 136.5
                y: 107.0
                z: -20.5
                yaw: 90.0
                pitch: 0.0
            yellow:
              0:
                x: 115.5
                y: 107.0
                z: -20.5
                yaw: 0.0
                pitch: 0.0
            lime:
              0:
                x: 99.5
                y: 107.0
                z: -20.5
                yaw: 0.0
                pitch: 0.0
            green:
              0:
                x: 78.5
                y: 107.0
                z: -20.5
                yaw: 0.0
                pitch: 0.0
            light_blue:
              0:
                x: 78.5
                y: 107.0
                z: 16.5
                yaw: 0.0
                pitch: 0.0
            dark_blue:
              0:
                x: 78.5
                y: 107.0
                z: 37.5
                yaw: 0.0
                pitch: 0.0
            purple:
              0:
                x: 99.5
                y: 107.0
                z: 37.5
                yaw: 0.0
                pitch: 0.0
            magenta:
              0:
                x: 115.5
                y: 107.0
                z: 37.5
                yaw: 0.0
                pitch: 0.0
            pink:
              0:
                x: 136.5
                y: 107.0
                z: 37.5
                yaw: 180.0
                pitch: 0.0
            gray:
              0:
                x: 136.5
                y: 107.0
                z: 16.5
                yaw: 180.0
                pitch: 0.0
          all:
            0:
              x: 0.0
              y: 0.0
              z: 0.0
              yaw: 0.0
              pitch: 0.0