waiting_room:
  world: 'world'
  spawn_point:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  border:
    radius: 200.0
    damage: 0.0
    damage_buffer: 0.0

games:
  pvprun:
    maps:
      test:
        enabled: true

  skywars_rush:
    maps:
      test:
        world: 'world'
        enabled: true
        center:
          x: 0.0
          y: 0.0
          z: 0.0
        border:
          radius: 100.0
          damage: 0.0
          damage_buffer: 0.0
        spawnpoints:
          0:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 0.0
            pitch: 0.0
